### ISSUE TITLE
Define semantics for overlapping backend paths

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#148]
What should happen if a backend is mapped to a path which is contained by another backend's path?

Could this be useful, for example to allow data to be written to a path inside a backend which is otherwise not writeable?

**Comment by sellout** [comment]
We have decided on semantics for this now – we don’t allow it. Some backends allow for this, but that is up to the backend.

What we still have to do here is update the config format to make specifying such nested backends impossible (we already use such a data structure in slamengine, we just need to serialize it).

**Comment by jdegoes** [comment]
Not sure this is the ticket for it, but some users do not like the storage of notebooks inside the database, and do not want to give their end-users write permissions. Which we can address *without* nested backends if we support (a) views / symlinks, and (b) notebooks that reference a foreign mount.

Another idea might be to carve out the different permissions, e.g. `(Read | Write)`, and mounts would always be with respective to a combination of permissions, such that you could mount a `Read` system and a `Write` system at the same path, because there would be no overlap.

In any case, I think it's time to clean up a lot of these old tickets and re-open them when requirements have been better thought out and defined.
