### ISSUE TITLE
data: translate extended data types to/from JSON

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#255]
Each backend will likely support a set of datatypes in documents which won't all be representable in pure JSON.

For example, MongoDB types that we almost certainly want to support include dates, timestamps, and "binary data".

We should find/invent a scheme for representing these values which isn't tied to a particular backend, and which will be compatible with as many JSON parsers as possible. This will also allow our own front-end to be intelligent about how it presents dates in particular.

For now, we accept/produce these values using MongoDB's [strict mode](http://docs.mongodb.org/manual/reference/mongodb-extended-json/).

**Comment by mossprescott** [comment]
As far as I can tell, there are still no good ideas out there about how to encode rich data types in JSON, so here's a proposal that's fairly simple and un-creative.

*In short, I suggest we embrace & extend the MongoDB "strict mode" JSON encoding, adding a few types of our own, but also make a more consistent effort to hide the details from users.* Read on for motivation and details.

First of all, we should make a distinction between the format for data exchanged by SlamEngine with machines (via the Web API, primarily), and how data is presented to users. In short, there are at least three different ways data is exposed by SlamEngine:

1. internally, and eventually to Scala/Java integrators, data is stored in our `Data` ADT. No encoding is required.
2. in the Web API, all data should spec-compliant JSON, with non-native data types encoded in an unambiguous way.
3. when presented to users, data can be formatted in whatever way is likely to be useful and not confusing. This includes query results shown in the REPL and the admin UI, and in CSV files written by the admin UI, as well as data shown in SlamData.
4. An exception to that rule is when data is *entered* via the repl, in which case we need an un-ambiguous format and the ability to enter data of every possible type. The most obvious approach is to use the Web API's JSON format for data entry in the REPL, even though this will be inconsistent with how query results are shown.

As of now, `Data` includes these types for which there is no corresponding native JSON type:

1. `Timestamp`: a UTC date-time value, with millisecond precision
2. `Date`: a (Julian calendar) date, specifying year, month and day
3. `Time`: a time of day, with millisecond precision
4. `Interval`: a duration value time in terms of elapsed time, with millisecond precision
5. `Binary`: a stream of uninterpreted 8-bit binary data (not really used yet)
6. `Set`: presumably analogous to a JSON array but with unique elements and unspecified order (not really used yet).
7. `Int` (as distinct from JSON's arbitrary-precision floating-point number, which maps well to `Dec`)
8. `ObjectID` (actually missing from `Data`, but seems to belong there)

It's worth noting that the above types mostly correspond to MongoDB's BSON. It's likely that when other backends are supported, this list will grow a bit to accommodate additional native types. Whatever encoding we use should be flexible enough to add additional types as needed.

Our encoding needs to be (from most to least important):

1. *valid JSON*
2. *precise and unambiguous*, so we can reliably transfer data using it without corruption
3. *extensible*, so we can add types later as needed
4. *simple*, so we can easily implement it on the back-end and front-end, and easily document it for others
5. *efficient*, so as not to waste too much space and bandwidth
6. *readable*, or at least not too horrible to look at in its raw form

All of which suggests using raw JSON for the types it supports, and using a simple encoding for just the types listed above. As it happens, MongoDB has invented such an encoding, ["strict mode"](http://docs.mongodb.org/manual/reference/mongodb-extended-json/), and it already handles about half of the extra types. 

The result would look very similar to what's currently used in some of our integration tests. For example: https://github.com/slamdata/slamengine/blob/master/it/src/test/resources/tests/days.data

The next comment will contain a couple of issues that come up if we decide to use a variant of that encoding.

**Comment by mossprescott** [comment]
Open questions if we adopt a variation of MongoDB's "strict mode":

## Name conflicts

First, strict mode uses `$date` for what we're calling `Timestamp` (to be consistent with SQL syntax). Our `Date` type represents time-less date values, which MongoDB doesn't deal with. And to make matters worse, MongoDB has a separate `$timestamp` type which we don't use. We'll have to choose either:
1. use `$timestamp` and `$date` to be consistent with our own types, but incompatible with MongoDB.
2. use `$date` and *some other key* to be compatible with MongoDB, but confusing our users.
3. change our own types to match MongoDB's (but be incompatible with SQL).

Option (1) seems best. If we use our own names consistently, there will be a simple mapping from our encoding to MongoDB's (in case that's ever needed) and we keep things simple for us and our users.

## Escaping

Second, certain keys (`$date`, `$interval`, etc.) become unavailable, or otherwise need to be escaped in some way. MongoDB dodges this issue by simply not allowing field names to ever start with `$`. In the long run, I don't think we can afford to do that, but for now we effectively have the same limitation, at least for the MongoDB back-end.

I suggest we put off dealing with this and for now just enforce the same limitation: keys cannot start with `$`, period.

## Numbers

The native number type for JSON is arbitrary-precision decimal, which maps well to our `Dec`, so the obvious choice is to translate raw numbers to Dec, and use an encoding for integers. But this would mean even the simplest results are likely to contain a lot of entries like `count: { "$int": 0 }`. The seems wasteful and inconvenient, so I propose a slightly tricky alternative:

Strictly interpret numbers without decimal points as `Int`, and require a decimal point (and trailing zero, as required by the JSON spec) to signify `Dec`. That is, `{ count: 0, weight: 1.0 }` would represent the values `Int(0)` and `Dec(1)`.

This goes somewhat against the spirit of the JSON spec, and will require any JSON parsers and serializers we use on both sides of the API to preserve information on how many digits were present in the source. If JSON tools tend to discard trailing zeros, then it could cause subtle and insidious data integrity problems. (At least one tool, [JSONLint](http://jsonlint.com), does exactly that.) Perhaps that could be overcome by having an option to force the unambiguous encoding, but, yeah.

I'll do some research and see how practical this seems to be, for SlamEngine at least.

**Comment by jdegoes** [comment]
At a high-level, this makes sense, but I think there are actually 2 proposals here:

1. **Strict-mode input / output**. In this mode, everything is fully unambiguous and specified. There are no two possible interpretations of anything.
2. **Non-strict-mode input / output**. In this mode, our choices reflect a desire to make the common cases simpler and less verbose. It's possible this mode might not even support all data types.

In strict-mode, even `Int` would be unambiguously specified (however verbose), and users could also embed JSON documents with field names like `$date` (which would otherwise be impossible), and have those properly escaped so the data would survive unscathed in any backend.

These two different "modes" could be unified, e.g. by sending (partial to complete) schema information together with JSON, which gives the ingestion API a way to interpret the JSON with the correct types. 

Although, I'm not sure if that's a good idea. The main use for a strict-mode is probably when the data is coming from something richer than JSON -- e.g. JSON or XML with application-defined structure, data from an RDBMS, etc. In this case, it seems tempting to go beyond just strict mode and offer a way of eliminating all the massive redundancy in JSON, i.e. leverage one of the many formats such as Avro or Parquet which permit factoring out redundant schema information and specifying richer types.

In any case, I don't think strict-mode or non-strict mode need be compatible with MongoDB, because we can add an API which accepts BSON, which is completely unambiguous and probably how a MongoDB user would choose to import data.

The question really is, which one is this ticket? I'd argue it's *non-strict mode*. Reason being, our exist JSON API is *already non-strict*.

In light of that, more to follow in my next comment.

**Comment by jdegoes** [comment]
In non-strict mode, I'd propose JSON input / output (in strict-mode, it could be JSON DSL, JSON with attached schema information, or non-JSON format).

I'd propose the following representations for the common types:

* **Int**. `Int`s are rendered without decimal points, and numbers without decimal points are parsed as `Int`s.
* **Dec**. `Dec`s are rendered with decimal points (and a trailing zero if JSON mandates it -- can't remember), and numbers with decimal points are parsed as `Dec`s.
* **Date** / **DateTime**. `Date`s and `DateTime`s are rendered as ISO8601 date / date-time strings, and strings that are valid ISO8601 date / date-times are parsed as `Date`s / `DateTime`s.
* **Interval**. `Interval`s are rendered as ISO8601 interval strings, and strings that are valid ISO8601 intervals are parsed as `Interval`s.
* **Time**. `Time`s are rendered as ISO8601 time strings, and strings that are valid ISO8601 times are parsed as `Time`s.

I'd propose not supporting ids, binary data, and sets in non-strict mode.

I think it's an oversight that we don't have an `Id` data type (maybe something like `case class Id(value: Bson)`), and we should probably add that. `Data` should always reflect the type system.

It's clear we need a strict mode, too, especially for importing data from other back-ends (including RDBMS). I'd be fine with your above proposal (tweaked so it's completely unambiguous), although feel free to consider other alternatives. It's not like we are forced to choose only one -- at some point a generic data ingestion API might be capable of handling MongoDB strict-mode JSON, BSON, Avro, Parquet, etc. (in fact, I'm pretty sure there's at least one library out there which does some unification and might be useful for generic data import / export).

**Comment by mossprescott** [comment]
Thanks, that's all really helpful. Your suggestions about "non-strict" encoding make sense and should be easy to implement.

Actually, I think this issue is about both, since the main need at the moment is for integration tests, which pretty clearly need the "strict", unambiguous mode, but if we make that representation more verbose, we're going to need "non-strict" mode for the REPL/UI to keep it usable (for one thing, we've already had complaints about the presentation of dates).

Something schema-based (like Avro) looks promising for input, but doesn't help with outputting schema-less data, I don't think.

So here's a plan for this ticket:

1. go ahead with an unambiguous "strict" encoding, for the time being using it in these places:
   - integration tests, for both test data and expected results
   - in the REPL and the API, when data is accepted as input
2. also implement a "readable" encoding, and use it wherever results are presented to the user:
   - in the REPL and the API for results
   - in the admin UI, for results and for CSV exports

In the future, I think we'll want to switch the API to use the strict encoding for output and have the front-end interpret that. For that matter, the API should probably have a `format` option for both input and output, and support a variety of formats as you suggested.

**Comment by jdegoes** [comment]
I think this is a good plan of attack, we need both strict and fuzzy modes. For the REPL, please make the default "fuzzy", but we can control that with a variable `set strict=true|false` or something. 

The admin UI should definitely use strict mode so it can properly render data types (e.g. DateTime), and SlamData 2.0 should also use strict mode for the same reason. Applications expecting pure JSON output can use fuzzy mode. We should switch between them using the `Accept` header (rather than a query string flag), and using custom mime types defined by us (e.g. text/x-json-strict).

I'm concerned by the data explosion of JSON + strict mode. Probably OK for now, since no matter what we need a JSON fallback that's unambiguous (so we'd have to implement it at some point). But in the mid-term we need a format that allows us to both precisely represent types as well as avoid repeating metadata whenever we don't have to, because right now we could easily be turning a 1kb document into a 100kb document, which is just not viable.

Lots of solutions out there, just need time to find the one that fits best.
