### ISSUE TITLE
planner: surface failures in logical plan phases related to unbound variables somehow

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#414]
Currently any "bound" phase can only be applied to plans that include no unbound `Free` instances. If any occur, an exception is thrown (and not handled well). This isn't happening at the moment only because the compiler never produces such a plan.

At a minimum, these errors should be captured, probably using `-\/`, But it's not clear how this would fit into the rest of the Monad stacking that's going on.

Furthermore, it might be useful for these phases to be able to handle "fragments" of plans that have these unbound variables in them, say by supplying a function to handle any unbound variable.

**Comment by sellout** [comment]
I think the way to handle this is to not error, but rather apply the phase to the free variable. EG, instead of
```scala
case FreeF(name) => vars.get(name).getOrElse(sys.error("not bound: " + name)).point[M]
```
use
```scala
case FreeF(name) => vars.get(name).fold(loop0)(_.point[M])
// where `loop0` is what we do for other nodes uninvolved in binding
```
and change `WorkflowPhase` to something like
```scala
case FreeF(name) => state(-\/(InternalError("not bound: " + name)))
```
IE, in a bound phase, the handling of free variables is left up to the phase function. Granted, all of this phase stuff is going away, but I am doing basically the same thing with bound folds, and I’m currently taking this approach.
