### ISSUE TITLE
compiler: GROUP BY should be compiled to something that distincts by something or other

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#459]
This is a well-known issue, but I haven’t found a bug associated with it.

In a query like `select city from zips group by city` we do
```js
db.zips.aggregate([
    { "$group" : { "city" : { "$push" : "$city"} , "_id" : "$city"}},
    { "$unwind" : "$city"},
    { "$project" : { "city" : "$city" , "_id" : false}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.find()
```
when really we want
```js
db.zips.aggregate([
    { "$group" : { "_id" : "$city"}},
    { "$project" : { "city" : "$_id" , "_id" : false}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.find()
```
IE, we shouldn’t unwind unaggregated fields if those fields are part of the group key.

**Comment by jdegoes** [comment]
More detail on the intended semantics and implementation:

 1. After parsing to SQL ADT, but before compilation to logical plan form (let's discuss!?), we special case `GROUP BY`. 
 2. We look at all the terms that make up the `GROUP BY` product. 
 3. For each of these terms, we do a top-down search for equality matches inside the `SELECT` clause.
 4. If we find a match `e`, we replace the expression `e` with `PICK(e)`, where `PICK` is a new many-to-one aggregation defined to return an arbitrary (but not necessarily random) element from the provided set.
 5. On MongoDB, we implement `PICK` with `$first`. 

Thus, the query:

```sql
select city from zips group by city
```

will be de-sugared to:

```sql
select pick(city) from zips group by city, state
```

**Comment by jdegoes** [comment]
If it turns out to be not that difficult, we should also optimize in the MongoDB planner so as to convert something like this:

```json
{$group: {
     _id: "$city",
    count: {$sum: 1},
    city: {$first: "$city"}
}}
```

into this:

```json
{$group: {
     _id: "$city",
    count: {$sum: 1}
}}
{$project: {
    city: "$_id",
    count: "$count"
}}
```

Secondary note: the "desugaring" will require access to the table-bound identifiers in order to compute equality for joined data sets. So I guess it would have to be done on the annotated tree. An alternative would be doing this on the LP, but maybe only when the input is SQL and not LP.

**Comment by mossprescott** [comment]
So I went spelunking on the internet and the thesaurus for alternative names for the "pick" function, and the best alternatives I could come up with are `Arbitrary` and `Any`. Assuming we don't plan to implement `any` and `all` as functions over sets of booleans, then I would suggest `Any` as being fairly clear but also short and easy to say.

In case someone wants to dive deep, here's my complete least of discarded alternatives:
- **Arbitrary**
   - *pro*: probably the clearest and most accurate term
   - *con*: long
- **Any**
   - *pro*: short and sweet; nearly as clear as arbitrary
   - *con*: confusion with `any: Set[Boolean] => Boolean`; note: MongoDB provides `$all` but nothing called "any"
- **Pick**
   - *pro*: short
   - *con*: if anything, suggests some method of picking
- **First**
   - *pro*: clear connection to the MongoDB operator
   - *con*: overly strong connection to the MongoDB operator; suggests it selects the first element according to some well-defined ordering
- **Arb**
   - *pro*: suggests arbitrary, but short; analogous to `avg`
   - *con*: not very obvious what it abbreviates
- **Choose**
   - *pro*: short, analogous to e.g. ScalaCheck's `Gen.choose`
   - *con*: confusion with the binomial coefficient function; seems to suggest some method in the choice
- **Some**
   - *pro*: short and sweet; nearly as clear as arbitrary
   - *con*: fatally confusing with `sum`; confusion for us with Scala `Option`
- **One**
   - *pro*: short
   - *con*: suggests the number 1 rather than "one value"
- **A/An**
   - *pro*: now we're talking short; reads really well (`select a(city), an(author) from ...`)
   - *con*: probably too short and/or cute, especially `a`, or just reads as a letter rather than a word; grammatically awkward

**Comment by jdegoes** [comment]
:+1: for `arbitrary`.

We need `ANY` / `ALL`, although they are sometimes also called `EXISTS` / `FORALL` (they will be used with MRA a LOT in `WHERE` clauses).
