### ISSUE TITLE
mongodb: runtime errors when null and undefined values occur in JavaScript

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#466]
When we generate JavaScript (for `where` selectors and map-reduce ops), we don't currently guard against dereferencing `null`, `undefined`, or non-object values.

For example:
```sql
select * from zips where length(foo.bar) > 0
```

**Comment by sellout** [comment]
Well, sometimes we have to – EG, `select meh + 4 from zips` is handled without any JS (so we get Mongo’s `"0": null`, but if we do `select meh + 4, length(meh) from zips`, suddenly both projections are handled in JS and we probably don’t want `meh + 4` to be handled differently just because of other projections that happen to exist.

The other option is to basically do _everything_ in a `mapReduce`, to get true cross-backend consistency, but is the performance penalty worth that? Especially when we don’t yet support any other backends?

**Comment by jdegoes** [comment]
Performance is definitely a valid reason for cheating! Albeit, any difference which could be dealt with in a streaming fashion needn't lead to a map/reduce (once we have some streaming machinery). e.g. `null` resulting from a numeric value could be re-interpreted as undefined. But that's far beyond our current scope, unfortunately.
