### ISSUE TITLE
mongodb: runtime error with wildcard and more than one other field

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#497]
```sql
select *, city, pop
  from zips
  where pop > 1000
```
gives `java.lang.RuntimeException: cannot merge class slamdata.engine.physical.mongodb.Workflow$$Map with class slamdata.engine.physical.mongodb.Workflow$$Match`.

The same query with just `select *, city` works as expected.

**Comment by mossprescott** [comment]
This is no longer failing but instead producing a nonsensical $FoldLeft, and no results.

Removing the `where` makes it work, so this is presumably related to the handling of ShapePreservingBuilder (see #603).

**Comment by sellout** [comment]
“nonsensical $FoldLeft” implies `Workflow.merge`, and the only place we call that is `toCollectionBuilder(ShapePreservingBuilder)`, so removing the `where` would certainly make it go away.

I think the problem is more that we don’t yet have cases in `objectConcat`/`merge` to deal with `SpliceBuilder`. We build up this:
```
ShapePreservingBuilder
├─ SpliceBuilder
│  ├─ SpliceBuilder
│  │  ├─ CollectionBuilder
│  │  ├─ Expr
│  │  ├─ Doc
│  │  ╰─ Doc
│  ├─ Expr
│  ╰─ Doc
├─ ExprBuilder
│  ╰─ CollectionBuilder
╰─ Op($Match($Read(Collection("")),Selector.Doc(BsonField.Name("_0") -> Gt(Int64(1000)))))
```
And there is nothing that will merge that correctly. `SpliceBuilder`s shouldn’t get stacked like that in the first place, which happens because of missing `objectConcat` cases.
