### ISSUE TITLE
admin: improve JSON rendering in admin GUI

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#592]
Now that we have two ways of formatting JSON result, "readable" and "precise", we should support options to select the output format in the admin UI and in the REPL. At the moment, both are hard-coded to produce the "readable" format, but there is code to support either (just no interface).

In the Admin UI, this would probably take the form of a checkbox that appears with the results table, and immediately re-renders the contents.

In the REPL, it would probably be a command, e.g.`set format = precise`.

**Comment by jdegoes** [comment]
I don't think it should be a choice. The admin UI should always use "precise" for rendering the table, and "readable" for dumping to CSV. The REPL can definitely benefit from a choice for either.

**Comment by mossprescott** [comment]
Let's see if you still feel that way after you've seen what it looks like ;)

Seriously, the table can use the actual `Data` instances to do nice rendering if it wants to. The question is whether it should match either of the JSON formats.

**Comment by jdegoes** [comment]
The CSV has to be flat, which limits the ways we can render it (we certainly don't want metadata in the column headers!). Probably we should be aiming to render it in a way Excel can read it, which in an ideal world would be *ISO8601*-compliant. But yeah, admin UI could grab the data back in any (precise) format to have enough information to render compliantly.

I think the main point of the table rendering is to create as simple, clean, and faithful representation of the data as possible. Not to invest a lot of time here, but it probably means rendering dates in a friendly fashion (instead of rendering them as timestamps), rendering strings *without* the quotes, rendering ints without the trailing point or zeros, rendering both ints and decs in a way the user can distinguish between them and strings, etc. I'll make sure all these sorts of things are spec'd up for the front-end, for admin it's less crucial.

**Comment by mossprescott** [comment]
"Readable" plus not showing quotes around strings, which is what the admin UI is currently doing, accomplishes all of that except you can't tell numbers and strings apart. And it occurs to me that we talked about right-aligning numbers, which would take care of that. Actually, we could extend that to most non-string types, I think.

Let's look at it in person soon and see what makes the most sense.

**Comment by mossprescott** [comment]
Here's a preview:
![screen shot 2015-02-08 at 10 58 54](https://cloud.githubusercontent.com/assets/6147371/6097612/9f9243dc-af81-11e4-90c2-2d9a5d687f23.png)

**Comment by jdegoes** [comment]
This looks really nice. Albeit, it's unfortunate that what is obviously a date is being reflected as a timestamp, but since MongoDB can't store true dates, we'll have to accept that for now until we have a better solution.

**Comment by mossprescott** [comment]
After using this a bit and pushing the code around so the REPL could take advantage of it as well, I landed on a different idea, which is that the REPL should provide a mechanism to load and dump data in Precise JSON format (see #642), but both the REPL and the UI should display data in a readable but unambiguous form, which they can both accomplish by not sticking to JSON, and using the same alignment trick.

PR coming up shortly.
