### ISSUE TITLE
mongodb: failed conversion from BSON not handled gracefully

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#627]
BSON data coming from MongoDB may contain values that we cannot represent in our `Bson` type, either because we've chosen not to have a representation (JS values), or because the driver produces something we didn't anticipate (e.g. java.util.UUID, prior to #626). As of #626, this results in a bogus `Text` value being returned.

We should wrap these values in `SomeError \/ Bson`, and handle the failure upstream.

**Comment by mossprescott** [comment]
On reflection I don't think returning `\/` is the right fix. We are typically decoding shallow nested objects (query results), and we want to be able to show a partial result even if some of the leaves aren't decoded. Failing the whole result "row" because the value of one of the fields wasn't decoded doesn't seem much better than what we had before.

I can think of a couple of alternatives:

Have a way to embed failed values inside the result `Data`. We could have an `EncodingError` value which extends `Data` and mix it in with the real values. That would be simple but seems to pollute the `Data` type with something that doesn't really fit. And what would `EncodingError.repr` produce?

On the other hand, we could push the errors down one level in the result object. So `Data.fromRepr` would return `ListMap[String, (Error \/ Data)]` (which could obviously be "sequenced" to `Error \/ Data.Obj]` so we wouldn't lose anything. That would allow partial results to be presented. This would nicely handle the common case of a query result, with one exception: when results are nested under `value`, we'd be back to "all-or-nothing" failure.

**Comment by sellout** [comment]
Mwahaha! Finally an excuse to make `Data` a functor. With a `FaultTolerant` fixed point:
```haskell
data FaultTolerant left right
  = Success (Fix right)
  | Failure left
  | PartialFailure (right (FaultTolerant left right))
```
(Scala is left as an exercise for the implementer.)

So we then have `def fromRepr(obj: DBObject): FaultTolerant[Error, Bson]`.

`FaultTolerant` would have some operations to convert `PartialFailure` into either failure (`requireSuccess :: FaultTolerant l r -> Either l r`) or success (`beLenient :: FaultTolerant l r -> Fix r -> Fix r`), collect failures, etc. I wouldn’t be surprised if this already exists, but I’m not familiar with it.

**Comment by mossprescott** [comment]
That's clever, but assuming it was intended to be taken seriously, I can see two problems:

We're already worried about the overhead of translating to/from `Data` when streaming results from MongoDB (see #612). This seems like more overhead, specifically one `Success` and one `Fix` object for each `Data` object, if I'm right about what scalac will do with this. My second proposal adds some overhead, too, but not as much.

It means all the users of our MongoDB Workflow library have to deal with YAFT (Yet Another Fixplate Type).

**Comment by sellout** [comment]
Actually, `Success` should probably be `Success (right (Fix right))`, but yeah, intended totally seriously (except for the Mwahahaha part). But, I think this could overall behave well for performance – if

1. `Bson`, `Data`, and `Json` are all functors,
2. we have functions like `Bson a -> Error \/ Data a` (rather than `Fix Bson -> FaultTolerant Error Data`), and
3. `DBObject -> bytes` is a hylo(?)morphism like `hylo(Json.toBytes, Bson.toData >>= Data.toJson, Bson.fromRepr)`.

That avoids creating intermediate structures, etc.

As far as fixplate types … I think it’s good to be consistent – if they have one, give them all to them. We just need to decide on what our favorite approach to those is and convert everything to use it.

**Comment by jdegoes** [comment]
1. I think all MongoDB values should be representable with `Bson`. `Bson` is just our sane, type-safe way of wrapping the Java client's `Any` type (yes, the API can return things with no common interface at all!).
2. I don't think polluting `Data` with `Error` is a good way to solve the problem. But having an R-style `NA` or `NotRepresentable` data type might be useful, if we believe that backends will support data types we have no desire to expose in a result set (a good example is Javascript, why-ever would you want to return JS in a result set?).
3. Converting from a backend format into our representation of the data should probably never fail. At least not in a fatal way that prevents the user from knowing what's inside a result set.

**Comment by jdegoes** [comment]
`Functor`-ifying things for now, if it helps, is fine with me. In the end, we will probably hand-write a converter from MongoDB Java client library 3.0's data structures to strings, just because it can't be done faster than that (at least, not without directly decoding the wire protocol, which is something we're not likely to have the resources to do anytime soon).
