### ISSUE TITLE
refactor: delete Workflow.merge

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#634]
`Workflow.merge` is messy, frequently incorrect, and just a bad idea. It’s only called in one place now, and that can be replaced with something much more specific.

It’s call site is `WorkflowBuilder.toCollectionBuilder(ShapePreservingBuilder)` and it’s used to try to push a ShapePreservingOp (match, limit, skip, sort) earlier in the workflow. Ideally, this would be handled by a `Workflow` optimization that just ensured that all the required fields for the op existed (with possible rewriting of the op). Then we could do the merge in `WorkflowBuilder` and let this optimization pass handle this later. That would eliminate a bunch of special casing in `WorkflowBuilder.toCollectionBuilder(ShapePreservingBuilder)` along the way and probably improve a wider range of queries.

In the interim, `Workflow.merge` could be cleaned up (disjunction instead of `sys.error`) and narrowed to focus on this one task (rather than attempting to merge arbitrary workflows). EG, when we call `Workflow.merge(src, chain(inputs, shapePreservingOp))` we know that we don’t need to preserve the fields on the right beyond the insertion of `shapePreservingOp`.

**Comment by mossprescott** [comment]
After looking at this briefly, and reviewing all the test failures that come from disabling that case in `toCollectionBuilder`, I think it will be fairly straightforward to handle re-ordering the ops in `finish` (the same place `deleteUnusedFields` is currently done).

I don't think we always want to push these ops as far up as possible. It makes sense to push up any op that reduces the size of the data (match, skip, limit), but it's less clear when it makes sense to push $sort up. A $project typically reduces the size of the data by trimming fields, so it seems like in most cases leaving a $sort after a $project would be better. In any case, we're in a better position to make that decision later, when the op has been materialized.

Pushing $match ahead of $simpleMap will involve inspecting the shape created by the simpleMap. This is currently dicey because JsMacro doesn't require the shape to be fixed, although in fact as far as I know we always use it that way. In other words, JsMacro is under-constrained. It would be better if $simpleMap's expression took the form of a concrete JsCore instance with some "holes" embedded in it. I guess I'm arguing for the *opposite* of HOAS, in a sense. Would like to discuss this with @sellout.
