### ISSUE TITLE
api: add import / export for csv

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#645]
`Accept` header should be used to detect CSV request, and `Content-Type` header should be used to detect CSV upload.

**Comment by jdegoes** [comment]
There's some very old, bad code I wrote for detecting CSV files: https://github.com/jdegoes/textype

I'm sure there's something better out there which can handle the many flavors of CSV.

**Comment by sellout** [comment]
When someone submits CSV for upload, are we going to parse a header like `foo.bar[0]` into a nested structure, or are we assuming the data is flat, and headers are simple field names?

**Comment by jdegoes** [comment]
I don't know of many tools which generate nested CSV names ([Gnip]((http://support.gnip.com/articles/json-to-csv-conversion-overview.html)) being one notable exception. That said, there's an argument to be made here: if we dump out CSV and nest column names (as I *believe* that Moss does in the Admin GUI, and which we will support as a return format from our APIs), we should be able to import that same data. So :+1:  for nested column names on import/export.

**Comment by mossprescott** [comment]
Gnip's approach to this problem is interesting (see http://support.gnip.com/articles/json-to-csv-conversion-overview.html). It doesn't seem very reversible, since they only use nested names when the same simple field name appears more than once, and they encode arrays of simple values as single comma-separated values.
