### ISSUE TITLE
switch over to http4s

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#675]
In the process, we can clean up some things:

 * Always use HTTP `Warning` header for warnings.
 * Always use non-200 HTTP status line for a one-line error summary.
 * Always put detailed error and warning messages in the response in a standardized way (e.g. `{response: a, errors: [], warnings: []}` or some such).
 * Recognize `Accept` and `Content-Type` headers and produce correct `Content-Type` headers.

**Comment by puffnfresh** [comment]
http4s :+1:

**Comment by mossprescott** [comment]
@jdegoes, @sellout: The way we handle paths is clashing with http4s.

In slamengine's `Path`, we make a distinction between a path like `./foo`, which is a relative path to a file called "foo", and `./foo/`, which is a relative path to a directory with the same name. This is somewhat tied into the way we map MongoDB collections to directories and files; two collections `foo` and `foo.bar` are presented as a file `foo` and a directory `foo` containing a file `bar` (so, three paths, `./foo`, `./foo/`, and `./foo/bar`.)

In http4s, paths are parsed out into lists of strings, with no trace of the trailing slash remaining. I could probably recover the raw path string from the URI, but it's not convenient.

I did some reading of the URI spec (always a good time), and there doesn't seem to be any particular semantics for trailing slashes, meaning that it's up to the server to interpret it, I suppose. It seems to be pretty common on the web for sites to redirect a path like `./foo` to `./foo/`, and I assume that comes from the convention in Unix where both paths refer to the same directory (and once upon a time it was common to alias `ls` to `ls -F` to display the trailing slash).

Because the behavior is probably surprising, I'm going to try to change the API so that you get the same results with or without the trailing slash. For now, I'll leave the result of `metadata` as is, which means you'll see both a file `foo` and a directory `foo/` as children of the root, but asking for the metadata of either will effectively produce the result for the directory. That won't hurt anything since we currently don't produce any metadata for files (just an empty list of children, although you could imagine returning the row count, etc.)

How's that sound?

**Comment by jdegoes** [comment]
I'd prefer to recover the raw path string, and / or submit a bug ticket or pull request to `http4s` to fix the behavior. There is only one unambiguous string representation that can distinguish between a file and a directory, and it's the trailing slash, so I'd regard `http4s` behavior as a bug (albeit one that's more forgiving than the alternative).

The PureScript path library I'm working on will also use the above precise and unambiguous grammar for parsing paths from strings (not that this should affect backend decisions, but it will just lead to compliance in all the APIs, as the front-end will only ever pass a directory with a trailing slash).

**Comment by mossprescott** [comment]
Fair enough. See https://github.com/http4s/http4s/issues/257.
