### ISSUE TITLE
mongodb: refactor MongoDBWrapper/EvaluatorImpl to a common implementation

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#679]
We have two "wrappers" for the MongoDB driver:

1. `MongoWrapper`, used by the `FileSystem` implementation mainly for enumerating collections and their contents
2. `MongoDBEvaluatorImpl`, used by `MongoDBEvaluator` mainly for running commands

Both wrap the driver's `MongoClient`, handling exceptions and putting effects in `Task`, etc. Both now need to deal with a "default" database name in one way or another. Neither is very effectively encapsulating anything now, and the common concerns are not represented in a consistent way.

**Comment by jdegoes** [comment]
@mossprescott @sellout After thinking about this some more, please let's not create any more "refactor tickets". Tickets are for features and bugs that should be scheduled and prioritized by a product manager (currently: me) based on business priorities. Since no customer will ever complain about architecture, per se, no refactoring tickets will ever be scheduled and prioritized (exceptions: ex-developer PMs familiar with the code base, which you can't count on).

Instead, when you see architectural problems like this emerging, fix them as part of the work you are doing. An analogy I like is an electrician who is changing an outlet and sees a uninsulated wire inside the outlet cover: she fixes it right away because she knows the hazard it poses; she doesn't make a note on the work order that she'll have to come back to the outlet some day to deal with the problem (she'd probably be fired for professional negligence if she did that!).

This means some tickets will take longer because you're working to improve the code base as you fix them, but it's better to do that than accrete a growing amount of technical debt. If a problem is emerging but a solution is not yet clear, it's OK to punt on that until the next time you're in that area of the code, but if a solution is clear then take that opportunity to implement it right then and there.

The exception would be for "process improvement" type things, which are longer-term projects that should be dealt with on your 10% process improvement time. I'll ignore any tickets which have the "process improvement" label on them, so you can use this to keep track of your own personal projects for long-term health of the code base.

How does that sound?

**Comment by mossprescott** [comment]
Yes, I completely agree from a process point of view. It's so easy to slip into the "I just need to get this done" mindset, but the right thing is to make the code better when the need arises.

I'm closing this ticket and I'll do the refactoring the next time I'm in the evaluator/filesystem which shouldn't be too far off.
