### ISSUE TITLE
invalid JS code generation

### ISSUE THREAD

**Issue by cryogenian** [slamdata/slamengine#716]
I've got an error when tried to get all fields in objects or array
```sql
select * from {{path}} where (
  foo{*} LIKE '%1%' OR 
  foo{*} = '1' OR foo{*} = 1 OR 
  foo[*] LIKE '%1%' OR 
  foo[*] = '1' OR foo[*] = 1)
```
```
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed 
with error 16722: 'exception: ReferenceError: Invalid left-hand side in assignment near 
'(function (__rez) { return __re'  (line 15)' on server localhost:27017. The full response is 
{ "errmsg" : "exception: ReferenceError: Invalid left-hand side in assignment near 
'(function (__rez) { return __re'  (line 15)", "code" : 16722, "ok" : 0.0 }
```

**Comment by sellout** [comment]
#715 has been fixed to the point that we now run into this on _every_ flatten. So, handling these two tickets in concert.

**Comment by sellout** [comment]
So, there’s a simplification we can do here on the Mongo side of things, but isn’t really correct in general:

In `mapReduce`, flattening works regardless of whether it’s an array or an object. #715 fixes that by doing a “typecheck” before flattening, but in a case like this, rather than trying to both treat it as an array and as an object, we could just unprotect it, and suddenly it works for both. In queries like those @cryogenian is currently generating, it’s a win, since the same condition is used in both the `[*]` and `{*}` cases. But in something like `select * from {{path}} where foo[*] = 1 or foo{*} = 2`, it will incorrectly also match when `foo[*] = 2 or foo{*} = 1`. We’d still need to do a “typecheck”, but it’d be a single wider one, `{} <= x && x < binary([])`.

Anyway, just thinking out loud.

**Comment by jdegoes** [comment]
I'm not sure why we are throwing away the type information to begin with. `[*]` and `{*}` are already typed to arrays and objects, respectively, and the semantics of MRA are to apply the operation to the types it makes sense with (and to produce undefined for everything else). Couldn't we just push that type information all the way through?

**Comment by sellout** [comment]
Mostly because pushing it through is a PITA (dealing with that PITA is what #715 is about).

My previous comment was just noticing that (with #715 fixed) the query in this ticket will create two temp fields – one where we attempt to arrayFlatten (and undefined otherwise) and another where where attempt to objectFlatten (and undefined otherwise) then check for the same values in either temp field – even though it’s impossible for both fields to be defined in the same record. In this (non-general) case, using JS’s agnostic flatten once (which we need to use for objectFlatten anyway) and just checking the one field would be simpler. But it’s not something I intended to do for this issue.
