### ISSUE TITLE
jenkins: restore configuration regularly

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#768]
Currently the slamengine configuration on the build server is not restored. So when users change it, those changes are permanent. The configuration needs restoring regularly so that the demo environment always reverts to its normal state.

**Comment by jdegoes** [comment]
Looks like demo environment is restored only on build, it should also be restored regularly -- maybe every hour or so.

**Comment by mossprescott** [comment]
The setup in Jenkins has been updated:

We now deploy the `lastSuccessfulBuild` of SlamEngine and SlamData, rather than the current contents of each workspace. This was necessary to avoid deploying junk in the event that the Jenkins builds ever fail (because we used to re-deploy only after successful builds, but now run it on a schedule).

The demo server is redeployed, using the default configuration, when there is a good build, but also every hour at approximately 50 minutes after the hour. This was formerly only done when there was a build of either the front- or back-end.

The demo datasets are reloaded (and temporary files are deleted) after builds and also every hour at approx. 45 minutes after the hour. This was formerly happening after each build, and every three hours during the day (6am, 9, 12, 3, and 6, MST)

This should ensure that things are in a good state most of the time, and especially if you happen to look at it near the beginning of any hour (when most meetings/presentations are likely to be scheduled :-P). Redeploying doesn't take very long, so there's not much harm in doing it more often, except that it will blow away any work-in-progress data and/or configuration, which could confuse users. If that's an issue, we can adjust the data-reload timing, separately from resetting the configuration.

Please re-open if the demo doesn't stay up better.
