### ISSUE TITLE
API: entire result brought into memory when it should be streamed

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#782]
This means we would run out of memory and fail to respond if a client tries to stream a very large result (larger than will fit in the heap in the form of `Data` values).

See https://github.com/slamdata/slamengine/commit/56ce4ac81a77c16e17a4ffcd5b9723c9c1a7b676#diff-b37ea18e5f5bbd36b3bb04e6f178f4e7R81.

The difficulty is how to handle failure. Currently, failures resulting from problems with the request are returned in `Process[PathTask, Data]`, so you have to consume the entire process to know if anything went wrong.

**Comment by jdegoes** [comment]
`Process[PathTask, Data]` (= `Process[ErrorT[Task, ?], Data]`) may fail on each chunk.

**Comment by jdegoes** [comment]
Well, more precisely, with such a type signature, you can fail during / between each chunk, before the first chunk, or after the last chunk.

**Comment by garyb** [comment]
Was this supposed to be assigned to me? :smile:

**Comment by sellout** [comment]
Argh – sorry about that – yeah, basically trying to not do 200 and then fail on the first chunk. I can fix this along with #774 (which I’m working on now).

**Comment by jdegoes** [comment]
OK, well, @mossprescott and @sellout need to divide & conquer, because we have the broken mount / metadata APIs, too — chat amongst yourselves about who should work on what, & reassign as you like.

**Comment by jdegoes** [comment]
If failure happens first, then you can easily embed the failure in `Process[PathTask, Data]`, in fact, it would be a good idea if the API could handle such "initial errors" which happen when you try to pull content (before deciding the response is necessarily 200).

If failures happen during streaming, well, technically the newline-delimited formats can handle that via HTTP chunking. The strict `application/json` format can't handle that.

**Comment by mossprescott** [comment]
So I got part of the way to a simple solution and then ran into the reason this doesn't work (obviously, in hindsight).

If the process simply halts, then we know there are no results to stream, so I simply run it for its (empty) effects, and handle the resulting error.

On the other hand, if the process seems to be capable of producing values, then I need to transform the `Process[PathTask, Data]` into a `Process[Task, Json]`, which I can give to the http4s machinery to be consumed to produce the response. The problem is how to make the change of monad. What I'd like to do is map over the process and handle PathErrors within each Task, and then... magically have those values become the values of a Process with the right monad.

*I* know that `PathTask` has the effects in `Task`, but how do I make Process or http4s understand that what I'm doing make sense? @jdegoes? @sellout?

**Comment by jdegoes** [comment]
You need a natural transformation from `ErrorT[PathError, Task, ?] ~> Task`, which is easy to define but will hide `PathError`s in `Task`. :disappointed: 

I'm not sure what @sellout's refactoring looks like, but ultimately we want `ErrorT[MyError, Task, ?]` (or stricter: `ErrorT[MyError, Future, ?]`) pretty much everywhere we have `Task` now (for some type `MyError`), so we are precisely tracking errors in return types instead of relying on `Throwable`s. 

When that happens you'll probably have the same problem, albeit for a superset of errors than `PathError`.

What we would probably like to do eventually is used chunked responses so we can emit errors individually for each chunk. That would faithfully model the type and allow more flexibility and robustness (e.g. emit half a 1GB dataset before MongoDB server reset causes a connection error). Obviously that's way beyond the scope of this ticket.

So I'd suggest adopting the pragmatic semantics: if reading the first chunk results in no errors, well, we issue 200 and stream the rest. If reading the first chunk results in errors, issue the appropriate error type. This still raises the possibility the stream will disconnect later due to errors that have been folded into `Task`, but that's pretty inevitable with more major re-engineering.

By the way, `Process[PathTask, Data]` just says that every chunk will be wrapped in an `Either PathError ?`, which will be further wrapped in a `Task`. Which basically says that at every (asynchronous) chunk, you'll get an error or a value. Since chunks can be empty, you can also have errors at the beginning, between, and end. That's the right way to think about it.

**Comment by mossprescott** [comment]
Ok I'm on it. As usual, that makes enough sense once it's explained slowly.

**Comment by mossprescott** [comment]
@jdegoes: It's been slow going, and I still only have a partial solution.

What I'm missing now is a way to consume the initial output so I can check for these failures. My initial attempt works only if the failures come back in Process (which we do sometimes, confusingly), not if they come back in PathTask, which seems like place we want them to be.

I can think of a not-very-smart way to do that (along the lines of `sampleMap` in prettify.scala), and I found a new combinator in Process, `unconstOption`, that seems to offer a cleaner solution, but that was just recently committed and isn't in the scalaz-stream version we're using.

**Comment by jdegoes** [comment]
You can call `uncons` to take off the head, which of course may fail, leading to your error; if it succeeds, you can emit that and concat it with the tail.

I'm sure there are other ways of doing this, too, not obvious what's the "best" way.

**Comment by mossprescott** [comment]
Right. My plan right now is to implement `uncons` and use that approach.
