### ISSUE TITLE
issue with larger HTTP GET queries on map/reduce output

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#793]
When the client uses the GET API, the client gets 200 OK but the result set is empty. 

When the admin GUI is used (which effectively writes the output into a defined location, AKA the POST API), then the result set is not empty.

See [here](https://slamdata.supportbee.com/tickets/5667289) for context.

Possibly, it's a problem with the "auto cleanup" logic. In the meantime, I will suggest the user use the POST API as a workaround, and verify it works correctly in client code.

**Comment by mossprescott** [comment]
As near as I can tell, the problem here is using `select *` with a join. I can do queries with joins and specific projections that produce more than 100k rows and 10MB of data without problems, but projecting `*` (even if the data size should be smaller) seems to blow up in MongoDB. I'm not exactly sure why that is; trying to capture plans so I can figure out what's wrong.

If that's the problem we're talking about, then using POST won't help.

**Comment by jdegoes** [comment]
Worth pursuing your current line of inquiry.

The user explicitly reported that the JOIN worked fine in the Admin GUI, but did not work via API. So maybe there are two issues or the user had some small query variation (`*` versus projections).

**Comment by mossprescott** [comment]
Taking a second look, I'm really not seeing any obvious problems here. @sellout: please look this over and comment.

I tried two similar queries: 
```sql
select a.foo, b.bar from a join b on a.id = b.id
select * from a join b on a.id = b.id
```
As expected, the results are the same except for the last op, which is either a project of two fields:
```
$Project
   ├─ Name(foo -> $left.foo)
   ├─ Name(bar -> $right.bar)
   ╰─ IgnoreId
```
or a simple map flattening of the left and right:
```
$SimpleMap
   ├─ Map((function (__rez) {
   │      for (var __attr in ((_ != null) ? _.left : undefined)) if (((_ != null) ? _.left : undefined).hasOwnProperty(__attr)) __rez[__attr] = ((_ != null) ? _.left : undefined)[__attr];
   │      for (var __attr in ((_ != null) ? _.right : undefined)) if (((_ != null) ? _.right : undefined).hasOwnProperty(__attr)) __rez[__attr] = ((_ != null) ? _.right : undefined)[__attr];
   │      return __rez
   │    })(
   │      {  }))
   ╰─ Scope(Map())
```

In both cases, that last op is preceded by a couple of unwinds:
```
├─ $Unwind(DocField(BsonField.Name("left")))
├─ $Unwind(DocField(BsonField.Name("right")))
```

In the simpleMap case, the unwinds end up getting inlined into the `map` function and the end result is it's about an order of magnitude slower (17s vs 1s if `a` and `b` are actually both `zips`). But I think that's expected.

**Comment by mossprescott** [comment]
On the other hand, a problem I did run into is that small errors tend to lead to horrible results.

For example, any competent query optimizer will turn this query into the query mentioned above: 
```sql
select a.foo, b.bar from a, b where a.id = b.id
```
And I'm in the habit of writing that, because there's less syntax to remember. But we don't optimize that, so you end up writing a temporary collection containing the cartesian product of the two sources, and then filtering out the matches. Which definitely blows up my local MongoDB instance.

I suspect something along these lines is what I was doing the other day, and *perhaps* played a role in the original user's problem. We may need to detect potentially pathological plans like this and warn/refuse to run them. This is especially important because once started it's difficult to recover (I repeatedly had to kill the mongo daemon, restart it, and then clean up temporary collections.) However I think we would need some collection statistics to make those decisions: how many documents in each source collection, maybe total collection data sizes, how many documents is OK to write to a temporary collection, etc.

**Comment by sellout** [comment]
Yeah, optimizing cross+filter is #281.

**Comment by jdegoes** [comment]
If customer confirms, this one can perhaps be changed to "detect and warn on massive implicit crosses generated by join key collisions".

**Comment by jdegoes** [comment]
Hmm, this one still not returning any results with the corrected query. @mossprescott Can you remote troubleshoot with customer today? Logs and screenshots in the ticket.

**Comment by mossprescott** [comment]
Sure. I'm taking a look and will get in touch with him.
