### ISSUE TITLE
make sure http4s / jetty do not have any connection timeouts due to inactivity

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#833]
It looks like anything longer than 30 seconds times out. Curl does this, but it may be the case that Jetty (or http4s) is also doing this. We need to ensure connections remain open for long-running queries that take more than 30 seconds.

**Comment by jdegoes** [comment]
Possibly related: 

<https://github.com/http4s/http4s/blob/master/jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala#L44>

**Comment by mossprescott** [comment]
Yes, it looks like the default timeout is 30 seconds. How long would you like it to be? Should it be configurable?

**Comment by jdegoes** [comment]
We can read it from the config, but let's default to infinity.

**Comment by mossprescott** [comment]
So this has been a fun troubleshooting exercise. It seems that http4s's Jetty backend, which we're currently using, just doesn't implement timeouts correctly. I've written up an issue for that.

So I turned back the Blaze backend, which was initially more appealing. But it has a different bug, with mounting multiple services at different path prefixes (which seems like a key feature, since it's the only way to get some kind of modularity for our growing services). I dug into that, figured out why it breaks us, and wrote up another issue for http4s.

But I also came up with a possible workaround that would allow us to switch to the Blaze backend, so that's what I'm pursuing now.

While I was at it, I also submitted an issue for the Jetty backend not handling exceptions/Task failure in any sensible way, since it turns out the Blaze backend does do that (producing a 500 immediately, which is what you want.)
