### ISSUE TITLE
default config location is incorrect on Mac

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#879]
Since adopting scala-pathy, we are trying to load the configuration from `currentDir` (e.g., `./Library/Application Support/SlamData/slamengine-config.json`), when the path should be relative to the user's home directory (Java's `user.dir`). pathy doesn't have a constructor for that, but perhaps it should.

**Comment by jdegoes** [comment]
The "current dir" in (purescript) pathy is meant to be a generic indicator for a relative path, not necessarily working dir (or user home or downloads folder or whatever). Probably some generic abstraction should exist for "relative to such and such a path", though I'm not sure if that should be inside pathy or not.

Also since this broke with not a word from the tests, maybe it's worth adding a test to ensure the config is read from the right location on the different platforms?
